name: R-CI (BSPM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: false

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev openjdk-11-jdk

    - name: Configure Java for R
      run: sudo R CMD javareconf

    - name: Setup BSPM and r2u
      run: |
        sudo apt-get install --no-install-recommends software-properties-common dirmngr
        sudo add-apt-repository -y "deb [arch=amd64] https://packagemanager.posit.co/cran/jammy/"
        sudo apt update
        curl -s "https://raw.githubusercontent.com/eddelbuettel/r2u/master/inst/scripts/add_cranapt_jammy.sh" | sudo bash -s
        sudo apt update
        sudo apt install -y r-base-dev
        
    - name: Install dependencies
      run: |
        R -e 'install.packages(c("lintr", "styler", "testthat", "remotes", "optparse", "rprojroot", "pkgdown"), repos = "https://r2u.stat.illinois.edu/ubuntu")'
        R -e 'remotes::install_deps(dependencies = TRUE, repos = "https://r2u.stat.illinois.edu/ubuntu")'
      working-directory: ${{ github.workspace }}

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.R_LIBS_USER }}
          !${{ env.R_LIBS_USER }}/testing
        key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-${{ matrix.config.r }}-
          ${{ runner.os }}-r-

    - name: Lint code
      run: R -e 'lintr::lint_package()'

    - name: Run tests
      run: R -e 'testthat::test_dir("tests/testthat")'

    - name: Style code
      run: R -e 'styler::style_pkg()'

    - name: Build package documentation
      run: R -e 'pkgdown::build_site()'
