name: R-CI (BSPM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: false

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev openjdk-11-jdk

    - name: Configure Java for R
      run: sudo R CMD javareconf

    - name: Setup BSPM and r2u
      run: |
        sudo apt-get install --no-install-recommends software-properties-common dirmngr
        sudo mkdir -p /etc/apt/keyrings
        sudo wget -qO- https://eddelbuettel.github.io/r2u/assets/dirk.eddelbuettel.asc | sudo tee /etc/apt/keyrings/cranapt.asc
        sudo wget -qO- https://eddelbuettel.github.io/r2u/assets/dirk.eddelbuettel.key | sudo tee /etc/apt/keyrings/cranapt.key
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends r-base-dev
        sudo apt update
        sudo apt install -y --no-install-recommends r-cran-r2u
        sudo add-apt-repository -y "deb [arch=amd64 signed-by=/etc/apt/keyrings/cranapt.asc] https://r2u.stat.illinois.edu/ubuntu jammy main"
        sudo apt install -y --no-install-recommends bspm
        sudo apt install -y r-base-dev r-base
        sudo apt update

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("lintr", "styler", "testthat", "remotes", "optparse", "rprojroot", "pkgdown"), repos = "https://r2u.stat.illinois.edu/ubuntu")'
        R -e 'remotes::install_deps(dependencies = TRUE, repos = "https://r2u.stat.illinois.edu/ubuntu")'
      working-directory: ${{ github.workspace }}

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.R_LIBS_USER }}
          !${{ env.R_LIBS_USER }}/testing
        key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-${{ matrix.config.r }}-
          ${{ runner.os }}-r-

    - name: Lint code
      run: R -e 'lintr::lint_package()'

    - name: Run tests
      run: R -e 'testthat::test_dir("tests/testthat")'

    - name: Style code
      run: R -e 'styler::style_pkg()'

    - name: Build package documentation
      run: R -e 'pkgdown::build_site()'
